name: Continous Integration


on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                node-version: 20.9.0
            - name: Install Deps
              run: npm install

            - name: Run Linters
              run: npm run lint

            - name: Run Formatters
              run: npm run format
