name: Continuous Deployment

on:
    push:
        branches: [ main ]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                persistent-credentials: false

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                node-version: 20.9.0

            - name: Install Deps
              run: npm install

            - name: Build
              run: npm run build

            - name: Deploy to production
            
              if: github.ref == 'refs/heads/main'

              uses: JamesIves/github-pages-deploy-action@v4
              with:
                branch: gh-pages
                folder: dist